version: '3.8'

services: 
  web:
    image: php:8.0-apache
    container_name: 'lamp_web'
    restart: always
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_USER: 'local_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'local_db'
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      UPLOAD_LIMIT: 999M
    links:
      - 'db:db'
    ports:
      - 8001:80
    
volumes:
  db_data:
    

    